### ISSUE TITLE
确实确实

### ISSUE THREAD

**Issue by woshishiq1** [StyGame/kapiao#1]
最早就用的你的，直到今年10月底的更新不能用了，才搜索群找的最新版本，没想到最新版本加了github地址真好，就不用烦恼那些群的消息了！那个人也借用你的源代码了吧，还说什么不喜欢看你弹窗的！有能力优化分支是好的，但在恶心人的基础上就。。。。！加油大佬

**Comment by qiabug** [comment]
本人将会开发到STY把弹窗去掉为止,仅此而已!
当然没有人可以强制谁喜欢谁!

**Comment by StyGame** [comment]
> 最早就用的你的，直到今年10月底的更新不能用了，才搜索群找的最新版本，没想到最新版本加了github地址真好，就不用烦恼那些群的消息了！那个人也借用你的源代码了吧，还说什么不喜欢看你弹窗的！有能力优化分支是好的，但在恶心人的基础上就。。。。！加油大佬

之前原作者的LOC能用，我就一直没管，懒得更新，最近那个dll挂了再更一下，也没人借用我源码，弹窗也是提示上号是否有卡票，也会有两个按钮用来区分是否初始化，避免比赛等场合用到卡票

**Comment by StyGame** [comment]
> 本人将会开发到STY把弹窗去掉为止,仅此而已! 当然没有人可以强制谁喜欢谁!

弹窗是正常需求，一般玩卡票都是老玩家，老玩家一般有多个号，想象一个场合，在卡票奔放过完任务，待会SSC或全民争霸，一不注意直接上比赛号，也无任何提示，跑到要拖漂的地方时一扭，发现自己开了卡票。
     那么问题来了：此时下号还来得及吗？
     那得看运气，毕竟比赛的时候一个车位撞不到都能被提交录像封号，更别说卡票
     也有可能没人提交录像，但保不准什么时候垃圾鹅加了什么逻辑暗检测

另外你可以让别人不用，但是不能讲我的封号，让别人不用是宣传，讲封号是诽谤，性质就变了
虽然美国联邦法中，没有诽谤法与侮辱法，但并不是表示可以恣意实行侮辱与诽谤。
就好比QQ飞车可以讲极品飞车不好玩，但是不能讲玩了极品飞车会得心脏病，是不是？

**Comment by qiabug** [comment]
> 弹窗是正常需求，充分提示，把选择的权利留给用户，一般玩卡票都是老玩家，老玩家一般有多个号，想象一个场合，在卡票奔放过完任务，待会SSC或全民争霸，一不注意直接上比赛号，也无任何提示，跑到要拖漂的地方时一扭，发现自己开了卡票。 那么问题来了：此时下号还来得及吗？ 那得看运气，毕竟比赛的时候一个车位撞不到都能被提交录像封号，更别说卡票 也有可能没人提交录像，但保不准什么时候垃圾鹅加了什么逻辑暗检测
> 
> 另外你可以让别人不用，但是不能讲我的封号，让别人不用是宣传，讲封号是诽谤，性质就变了 虽然美国联邦法中，没有诽谤法与侮辱法，但并不是表示可以恣意实行侮辱与诽谤。 就好比QQ飞车可以讲极品飞车不好玩，但是不能讲玩了极品飞车会得心脏病，是不是？

有多个号用软件上号做任务,软件不会处理你的弹窗就一直卡住上不了号. 还有你之前的弹窗秀你的爱情就伤害了一些单身狗,现在又改成喜欢你才能用了... 我的如果参加某些比赛不想用则把文件名加个前或后缀然后上号即可,当需要使用时再把文件名改回来.

另外我没有讲过你的封号.

**Comment by StyGame** [comment]
>

**Comment by StyGame** [comment]
> > 弹窗是正常需求，充分提示，把选择的权利留给用户，一般玩卡票都是老玩家，老玩家一般有多个号，想象一个场合，在卡票奔放过完任务，待会SSC或全民争霸，一不注意直接上比赛号，也无任何提示，跑到要拖漂的地方时一扭，发现自己开了卡票。 那么问题来了：此时下号还来得及吗？ 那得看运气，毕竟比赛的时候一个车位撞不到都能被提交录像封号，更别说卡票 也有可能没人提交录像，但保不准什么时候垃圾鹅加了什么逻辑暗检测
> > 另外你可以让别人不用，但是不能讲我的封号，让别人不用是宣传，讲封号是诽谤，性质就变了 虽然美国联邦法中，没有诽谤法与侮辱法，但并不是表示可以恣意实行侮辱与诽谤。 就好比QQ飞车可以讲极品飞车不好玩，但是不能讲玩了极品飞车会得心脏病，是不是？
> 
> 有多个号用软件上号做任务,软件不会处理你的弹窗就一直卡住上不了号. 还有你之前的弹窗秀你的爱情就伤害了一些单身狗,现在又改成喜欢你才能用了... 我的如果参加某些比赛不想用则把文件名加个前或后缀然后上号即可,当需要使用时再把文件名改回来.
> 
> 另外我没有讲过你的封号. 也可能是我2021.10.30的更新也以 EventReport.dll 这个文件注入, 现在抓包发现CRequestGetWorldInfoPara、CRequestFileCheckPara有一堆文件的校验值, 虽然目前还没有 EventReport.dll 这个文件, 但以免以后官方添加这个文件, 然后我就直接说"以免文件校验导致封号"

我认为一般知道要连续上号的有一定的基础知识，自然会先改名文件，
再说弹那个窗，也没说叫那个名字的是人名啊
文件校验其实屁用没有，只能查一些简单dll，随便一顿操作就废了，除非那帮人想大量误封

**Comment by qiabug** [comment]
> > 最早就用的你的，直到今年10月底的更新不能用了，才搜索群找的最新版本，没想到最新版本加了github地址真好，就不用烦恼那些群的消息了！那个人也借用你的源代码了吧，还说什么不喜欢看你弹窗的！有能力优化分支是好的，但在恶心人的基础上就。。。。！加油大佬
> 
> 之前原作者的LOC能用，我就一直没管，懒得更新，最近那个dll挂了再更一下，也没人借用我源码，弹窗也是提示上号是否有卡票，也会有两个按钮用来区分是否初始化，避免比赛等场合用到卡票
> 
> 另外，我也有渠道直接向项目组提交其他dll与检测其他dll的代码哟。

别胡说LOC是我的版本，原作者的是 DINPUT8 某些人有他的内部版本，好像可以提速卡漂，还可以自动秒松漂移键。

**Comment by qiabug** [comment]
> 

连续上号做任务是日常操作了 每天都要改了改去也很麻烦。

**Comment by StyGame** [comment]
> > 
> 
> 连续上号做任务是日常操作了 每天都要改来改去也很麻烦。

之后可以增加一个放C盘的标记文件，文件不存在就每次弹窗，文件存在就永不弹窗

**Comment by woshishiq1** [comment]
> > 
> 
> 连续上号做是日常操作了，每天都有任务要改来改去也很麻烦。

对我很同意syt的观点，对于开发者来说，你们都是大佬，我就是个普通玩家！不过我认为你有能力修改或者制作是好的。你的初衷也是好的，但是你不应该提什么syt的爱情窗口什么的！简单明了你这是无弹窗的，大家喜欢用谁的就用谁的不是很好吗？为什么要拉仇恨的！弹窗有弹窗的好处，不弹窗有不弹窗的好处！都是中国人搞那么多弯弯绕绕的多不好！不知道你们搞机不，我们搞机圈有个大佬制作搞机助手，也被人破解的直接删库跑路了，原因就是原作者加入了强制更新和一个收费很小的收费群，但是原作者缺并没有禁止群内人员传播此软件！你情我愿的而已，但是被大神给fake掉了！你们都是同理的

**Comment by qiabug** [comment]
> 对我很同意syt的观点，对于开发者来说，你们都是大佬，我就是个普通玩家！不过我认为你有能力修改或者制作是好的。你的初衷也是好的，但是你不应该提什么syt的爱情窗口什么的！简单明了你这是无弹窗的，大家喜欢用谁的就用谁的不是很好吗？为什么要拉仇恨的！弹窗有弹窗的好处，不弹窗有不弹窗的好处！都是中国人搞那么多弯弯绕绕的多不好！不知道你们搞机不，我们搞机圈有个大佬制作搞机助手，也被人破解的直接删库跑路了，原因就是原作者加入了强制更新和一个收费很小的收费群，但是原作者缺并没有禁止群内人员传播此软件！你情我愿的而已，但是被大神给fake掉了！你们都是同理的

STY大佬会怕被我指名吗?正所谓不打不相识. 现在看STY大佬这么喜欢更新,我就给他让路了,我也懒得更新了. 我这一路也是模仿他发邮件以及创建GitHub仓库, 暗示着我就是针对他爱情弹窗而来的. 这是来自部分单身狗玩家的嫉妒. 现在好了,也就这样了.

**Comment by 18335851706** [comment]
我想问一下，STY卡票安装器找不到游戏目录怎么办？win10专业版，打开后显示
C:\Flags.txt
拒绝访问。
给管理员权限后
GamePathRoot：C:\Program
1.安装卡票文件
2.卸载卡票文件
3.直接退出
输入操作选项:
系统找不到指定的路径。
已复制         0 个文件。
安装卡票完成
按任意键关闭

把STY卡票安装器放在C:\Program Files\腾讯游戏\QQ飞车\Releasephysx27再打开也是一样

**Comment by StyGame** [comment]
> 我想问一下，STY卡票安装器找不到游戏目录怎么办？win10专业版，打开后权限 C:\Flags.txt 拒绝访问。 给管理员后 GamePathRoot：C:\Program 1.安装卡票文件 2.卡票文件 退出 输入操作选项： 系统找不到直接指定的路径。键 已复制按0个 可选文件。 安装卡票完成
> 
> 一样把STY卡票安装器C:\Program Files\腾讯游戏\QQ飞车\Releasephysx27再打开也是

可能是由于飞车不是安装来的 是复制来的 也没有更新过 注册表中没有保存对应的游戏目录 这种情况下只能手动复制EventReport.dll到C:\Program Files\腾讯游戏\QQ飞车\Releasephysx27
