### ISSUE TITLE
询问下

### ISSUE THREAD

**Issue by woshishiq1** [StyGame/kapiao#12]
老大exe是单独作用吗，刚试了一下单独用exe没有作用，当然dll是生效的！特此反馈一下

**Comment by StyGame** [comment]
> 老大exe是单独作用吗，刚试了一下单独用exe没有作用，当然dll是生效的！特此反馈一下
应该都要有 可能要用管理员模式启动

**Comment by woshishiq1** [comment]
nopabula了，那我就主动关闭问题了，感谢老大
