### ISSUE TITLE
feature: 增加对市面上的单机版支持  目前这边自测单机版加载dll后会闪退

### ISSUE THREAD

**Issue by Xbs233** [StyGame/kapiao#22]

**Comment by StyGame** [comment]
单机版哪里下载

**Comment by a3332561487** [comment]
> 单机版哪里下载

我知道

**Comment by 307888629** [comment]
同测单机版无论是替换QUSEREX.dll还是EventReport.dll，在游戏开始的倒计时会卡一下然后闪退

**Comment by qingfengjiang** [comment]
单机版，倒计时卡2下闪退，求支持单机

**Comment by StyGame** [comment]
> 同测单机版无论是替换QUSEREX.dll还是EventReport.dll，在游戏开始的倒计时会卡一下然后闪退



> 单机版，倒计时卡2下闪退，求支持单机

我下载的单机版自带一个EventReport.dll可以使用 看起来单机版应该对应正式服3月的版本，使用较早期的dll即可
