### ISSUE TITLE
老大，狗策划好像又修复了

### ISSUE THREAD

**Issue by woshishiq1** [StyGame/kapiao#33]
11111气气气气

**Comment by woshishiq1** [comment]
除了github再挂个别的联系方式吧老大

**Comment by qzc666** [comment]
你这让卡飘之王情何以堪

**Comment by StyGame** [comment]
都打钱了吗，还没收到

**Comment by woshishiq1** [comment]
.......

**Comment by qzc666** [comment]
更新一下卡飘文件 谢谢

**Comment by qzc666** [comment]
> 都打钱了吗，还没收到

卡飘之王已经煽动群员打钱了，让你留个联系方式

**Comment by qzc666** [comment]
![6F58BH PSL0PJHHJ3XVD UP](https://github.com/StyGame/kapiao/assets/130905171/a49cecc2-173a-478c-bacf-7cedebd931c6)

**Comment by flying0228** [comment]
> 我靠,老大又没强制打赏，你不要在我楼下搞这些啊

他妈个杯 我已经卸载飞车了 玩不下去了

**Comment by StyGame** [comment]
> 我靠,老大又没强制打赏，你不要在我楼下搞这些啊

https://t.me/stydrak    TG群组
