### ISSUE TITLE
可以给游戏做一个翻译补丁吗？

### ISSUE THREAD

**Issue by KietTezend** [StyGame/kapiao#36]
我尝试了很多方法，但无法将游戏翻译成另一种语言，而且我不知道如何提取 .vfs 文件。
https://www.youtube.com/watch?v=ejWvdsC7kYQ
![image](https://github.com/StyGame/kapiao/assets/90176660/efc84bff-ae93-48e3-836d-f81abf51efe0)

**Comment by StyGame** [comment]
不能
