### ISSUE TITLE
无法在最新版本中使用

### ISSUE THREAD

**Issue by jiuwo123** [StyGame/kapiao#37]
在最新版本的飞车中，我将qusere这个dll文件解压进27文件夹后（32位版本），登录界面还是会显示卡票文件提示，但是当我真正游戏的时候，这个插件却是不能进行卡票，是我的操作有问题吗？还是什么原因呢？

**Comment by StyGame** [comment]
32位在几个月内会结束生命周期 不再更新 只能使用64位版本 登录64位飞车

**Comment by jiuwo123** [comment]
你好，今天是2024.9.14，我发现新的卡票文件解压后在游戏中无法使用，本想尝试7.14版本，但会自动更新。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StyGame/kapiao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月12日(星期天) 凌晨2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StyGame/kapiao] 无法在最新版本中使用 (Issue #37)





 
Closed #37 as completed.
