### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by unixcs** [StyGame/kapiao#8]
win10用户用了最新的卡票文件  跑两把就报错闪退，

**Comment by unixcs** [comment]
还有 请问大佬   6.14的公告什么意思，飞车安全团队开始严查 改卡票文件的用户了吗

**Comment by StyGame** [comment]
> win10用户用了最新的卡票文件 跑两把就报错闪退，

需要发报错的详细信息

**Comment by StyGame** [comment]
> 还有 请问大佬 6.14的公告什么意思，飞车安全团队开始严查 改卡票文件的用户了吗

与卡票无关 是增加各种乱封号的几率 和限制多个模式的参与 本来检测就垃圾经常自动减星 还非常自信的以为自己检测牛逼 以信誉分限制模式参与 试问玩飞车玩到一定水平 有几个没开没被封过号的 没被封过说明水平还不够或者后台比较硬

**Comment by unixcs** [comment]
[GameApp344cbb.txt](https://github.com/StyGame/kapiao/files/9137620/GameApp344cbb.txt)

闪退文件

**Comment by unixcs** [comment]
闪退文件：
[GameApp15a293.txt](https://github.com/StyGame/kapiao/files/9241845/GameApp15a293.txt)


大佬有空的时候 帮忙看一下。
使用最新这个版本的卡票，跑两把就闪退。
我的电脑：win10系统（cpu：amd 5600G）
同样的配置，年前使用您的老版本卡票文件，从未遇到过闪退现象。

另外，前两天去网吧（win7 电脑 + intelcpu + 独立显卡 ）开启卡票文件，游戏一切正常 也没遇到过闪退的情况。

不知道闪退是否和 `win10系统` +`amd apu` 或者是与飞车的不兼容 存在关联

**Comment by StyGame** [comment]
> 闪退文件：
> 
> 大佬有空的时候 帮忙看一下。 使用最新这个版本的卡票，跑两把就闪退。 我的电脑：win10系统（cpu：amd 5600G） 同样的配置，年前使用您的老版本卡票文件，从未遇到过闪退现象。
> 
> 另外，前两天去网吧（win7 电脑 + intelcpu + 独立显卡 ）开启卡票文件，游戏一切正常 也没遇到过闪退的情况。
> 
> 不知道闪退是否和 `win10系统` +`amd apu` 或者是与飞车的不兼容 存在关联

发报错文件要把最下面带自己号ID信息的部分删掉 从报错看 和卡漂附近的代码相关性不大，有可能是游戏本身不兼容amd的cpu指令集

**Comment by unixcs** [comment]
好的谢谢大佬回复，我也觉得是amd的优化没做好，飞车现在越来越拉了
